#!/usr/bin/env python3
# Copyright project_phoenix
"""
Primary launcher for the Gemini-branded desktop application.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from main import main


if __name__ == "__main__":
    main()
